apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  template:
    spec:
      containers:
      - name: bot
        args: ["src.next_rewards.main"]
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bots-secret
              key: DISCORD_BOT_TOKEN_REBASE
        - name: DISCORD_REBASE_BOT_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-bots-secret
              key: DISCORD_BOT_WEBHOOK_REBASE
